### ISSUE TITLE
Unable to set cursor

### ISSUE THREAD

**Issue by genius257** [anseki/jquery-plainoverlay#8]
Currently it is not possible to set cursor to "default" without forced CSS or changing the code

**Comment by anseki** [comment]
Hi @genius257, thank you for the comment.
Use `!important` to override `cursor` property.

**Comment by genius257** [comment]
yes, but what about individual cursor properties?

**Comment by anseki** [comment]
Since current version of plainOverlay doesn't support `cursor` option that works like [`zIndex` option](http://anseki.github.io/jquery-plainoverlay/#zindex), you have to access to the overlay element via internal object.

```js
$element.data('plainOverlay').jqOverlay.css('cursor', 'default') // jqOverlay is overlay element
```

Note that the `jqOverlay` doesn't contain a progress-element. If you use builtin progress-element (i.e. you didn't specify the [`progress` option](http://anseki.github.io/jquery-plainoverlay/#progress)) and you want to access the individual progress-element, use `jqProgress`.

```js
$element.data('plainOverlay').jqProgress.css('cursor', 'default')
```

**Comment by genius257** [comment]
Perfect! Many thanks

**Comment by anseki** [comment]
😄
